name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: yarn
        
    - name: Setup wasm pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: Build
      run: wasm-pack build
      
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: ./www
      
    - name: Build website
      run: yarn nx run app-game-of-life:build:production
      working-directory: ./www

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./www/dist/apps/app-game-of-life
